# Generated by Django 2.2.16 on 2022-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220221_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Расскажите, что вы думаете', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Зполните поле', verbose_name='Содержание'),
        ),
    ]
